### ISSUE TITLE
Horizontal scroll position resets on vertical scroll

### ISSUE THREAD

**Issue by Abstractn** [citrizon/ciui-web-scrollanim#1]
When a page has horizontal overflow and the view is positioned to the right, scrolling up or down resets the horizontal position to all the way back to the left.

Running version "2024-02-05" (version number may not be updated from code but I reinstalled the latest committed userscript).

see [video attachment](https://github.com/citrizon/ciui-web-scrollanim/assets/58334120/3ef08e60-c2d4-477b-98e9-a911117ceb89) for demo

**Comment by citrizon** [comment]
OK, Just made a fix, try it with the latest commit

**Comment by Abstractn** [comment]
Seems fixed, will close, thanks.
