### ISSUE TITLE
YouTube player volume

### ISSUE THREAD

**Issue by Abstractn** [citrizon/ciui-web-scrollanim#2]
YouTube's video player allows you to use the mouse scroll wheel to increase or decrease the volume when hovering over the volume slider.

The event listener for the volume slider still works but this script makes the page scroll down when lowering the volume.

**Comment by citrizon** [comment]
Interesting... I'll try to find a solution.

**Comment by citrizon** [comment]
Ok, i've found the solution, which is skipping the event function if the defaultPrevented value is true in the event object.

**Comment by Abstractn** [comment]
👍 fixed, I believe this also solved another issue that was so weird I don't even know how to describe it
