### ISSUE TITLE
Wrong scroll direction with overflowing nodes inside each other

### ISSUE THREAD

**Issue by Abstractn** [citrizon/ciui-web-scrollanim#3]
When scrolling within a section as the mouse hovers a block inside the section that allows horizontal scrolling the events of scroll up and down start controlling the horizontal scroll instead of the vertical one.

Steps to replicate:
(can be easily found in websites such as chatGPT chat or Google Gemini chat when the AI has generates a block of code with horizontal overflow)
- scroll up in the chat history
- a block of code overlaps with the mouse and is now being hovered
- scroll further
- -> the scroll direction is now incorrect (scrolling down goes right and scrolling up goes left)

**Comment by citrizon** [comment]
send me a video pls ty

**Comment by Abstractn** [comment]
I realized I can replicate this issue on my work laptop only and not my personal computer. My work laptop is a MacBook Pro 16 (2019) running Sonoma 14.2.1 navigating on Firefox and scrolling via trackpad. I'm unable to record the screen and in being so specific feel free to ignore the report.

**Comment by citrizon** [comment]
ok, as you say.
